### ISSUE TITLE
combine scss and css into single file?

### ISSUE THREAD

**Issue by apinfodesign** [wbeck32/phd2#18]
Added second scss file because necessary... combine style and new?

**Comment by wbeck32** [comment]
I'm trying to figure out if there's a tool or a script to use to merge two files so there are no overlaps. I know there is. I'll find it Friday.

I want to shove all of the existing css and the compiled scss into on ourawesomecss.css and minify it into one.

**Comment by wbeck32** [comment]
All the scss is now in one file! It compiles to one css file. I tried to include every single style, but I know I missed a few. I'm cleaning some of that up now.

I removed all of our unique styles for the navbars and buttons. It's probably best to go back to the bootstrap default and make the changes from there.
